name: C/C++ Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, msvc]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Compiler
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install build-essential

    - name: Build on Linux
      if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
      run: |
        g++ -std=c++17 -Wall -Wextra -o snake snake.cpp
        ./snake

    - name: Build on Windows
      if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
      shell: powershell
      run: |
        cl.exe /EHsc /W4 snake.cpp
        .\snake.exe
